# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b8b633b05996b1915632cf15f050f5c24668eca81e724b0859c40abdda4b790b4920c6d64439c0939059d2daa5e8da71ba72a7d40e8c3e39617caed8203fa14

test:
  secret_key_base: 7a90f6494cd50eda04381f263ffdd2eedba151cd6be8a0a0bae8da8ca5a29d46ea34d068d925f5ba442a3ce2f8997c56887f422f73ff040b742bb1f437f63c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
